### ISSUE TITLE
Session

### ISSUE THREAD

**Issue by jesperordrup** [JannikWempe/svelte-auth#1]
Hi Jannik

Nice example, thank you.

The session array - is the idea to keep track of user data server side? The array idea is just a simple example which would need to be replaced in a serverless setup, right?

**Comment by JannikWempe** [comment]
Hi, thanks for the kind words 🙏🏼

Yes, the user data has to be on the server side. The array is just stored in memory. Therefore all data is lost in case of a restart. In production, you would replace it with a database or a call to an authentication provider (Auth0 etc.).
