### ISSUE TITLE
Question about handleSubmit({ detail: {username, password} } )

### ISSUE THREAD

**Issue by shinokada** [JannikWempe/svelte-auth#4]
In the sign-in.svelte, you have an async function:

```
...
  async function handleSubmit({ detail: { username, password } }) {
		const response = await fetch('/api/sign-in', {
			method: 'POST',
			body: JSON.stringify({ username, password }),
			headers: {
				'Content-Type': 'application/json'
			}
		});

		const body = await response.json();
		if (response.ok) {
			// session from getSession hook will otherwise not be set before navigation
			// that would trigger redirect from /protected back to /sign-in
			$session = body;
			await goto('/protected');
		}
		error = body.message;
	}
```

Can you explain where `detail` come from?

When I use `handleSubmit( { username, password } ) `, it doesn't work. But I don't know why. 

Thank you.

**Comment by JannikWempe** [comment]
Hi,
yes, I can explain that.

The `dispatch('submit', { email, password })` in `SignInForm.svelte` dispatches an event with the `detail` being the email and password. In `sign-in.svelte` we listen for the `'submit'` event. The details of that `event` are accessible under `event.detail`. In the end: you have to know that Svelte provides details of a dispatched event (if any available – they are optional) under `event.detail`. `handleSubmit({ detail: { username, password } })` directly destructures that `event` into the `email` and `password`.

You can learn about the concept in the [Svelte Tutorial – Events / Component Events](https://svelte.dev/tutorial/component-events).

Does that answer your question?

**Comment by shinokada** [comment]
Thank you for your help.
