### ISSUE TITLE
Question about use:setType

### ISSUE THREAD

**Issue by shinokada** [JannikWempe/svelte-auth#5]
in the `Input.svelte`, you use `use:setType`:

```
<script>
...
function setType(node) {
  node.type = type;
}
...
</script>
...
<input
  use:setType
  {name}
  {id}
  {required}
  bind:value
  bind:this={inputRef}
...
/>
```

Why not use `export let type`? And a user can set it as `let type="email"` etc?
Could you explain you used the use:action here?
Thank you for your help.

**Comment by JannikWempe** [comment]
Valid question.

Try it and change `use:setType` with `{type}` (`export let type = 'text';` is already there). You will get an error `'type' attribute cannot be dynamic if input uses two-way binding`. I had that error, googled a little bit and found that workaround using the action.

Essentially that change makes the two-way binding a one-way bintding.

**Comment by shinokada** [comment]
Thank you for your answer. 

Don't you mind asking one more question about `bind:this={inputRef}`?

What are you expecting for the `inputRef`?
Why do you need it?

**Comment by JannikWempe** [comment]
You're welcome.

Sure, check out `SignUpForm.svelte`. `confirmPasswordInputRef.focus();` sets the focus to the confirmation input if it does not match the password. `export let inputRef = null;` in `Input.svelte` expose the reference to the actual HTML `<input />`. This enables to set the focus (and also other stuff) to the input from outside of `Input.svelte` (like it's done in `SignUpForm.svelte`).

**Comment by shinokada** [comment]
Thanks again.
You have a lot of tips to share.
Why don't you write more? I will be glad to read them.
Thank you for your help.

**Comment by JannikWempe** [comment]
Thanks for the kind words. 

I write quite a lot on [Twitter](https://twitter.com/JannikWempe) and [my blog](https://blog.jannikwempe.com/). Unfortunately the time of a day is limited 😅
